# Generated by Django 3.2.16 on 2023-06-09 11:46

import birthday.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0002_rename_birthdayform_birthdaymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdaymodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='birthdaymodel',
            name='birthday',
            field=models.DateField(validators=[birthday.validators.real_age], verbose_name='Дата рождения'),
        ),
        migrations.AddConstraint(
            model_name='birthdaymodel',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'birthday'), name='Unique person constraint'),
        ),
    ]
